# Document:
# http://simiki.org/docs/configuration.html

url: http://wiki.xiaohansong.com
title: Wiki | HanSong
keywords: wiki, markdown, linux, c, java, python, qemu
description: "HanSong's personal wiki, recording my little thoughts"
author: HanSong Xiao
theme: yasimple
