# Document:
# http://simiki.org/docs/configuration.html

url: http://wiki.xiaohansong.com
title: <a href="http://wiki.xiaohansong.com">Wiki</a> | <a href="http://xiaohansong.com">HanSong</a>
keywords: wiki, markdown, linux, c, java, python, qemu
description: "HanSong's personal wiki, recording my little thoughts"
author: <a href="http://xiaohansong.com">HanSong Xiao</a>
theme: yasimple
